Repository meower-media-co/Meower-Svelte, pull requests merged in 2022-12, with the labels that each got.

#52 Webhooks in Svelte
  src/lib/Post.svelte
  src/screens/Setup.svelte
Labels: enhancement, Medium priority, Svelte patch

#57 Fix dango profile picture being duplicated when it is selected
  CONTRIBUTING.md
  src/screens/Changelog.svelte
  src/screens/Profile.svelte
  src/screens/Setup.svelte
Labels: bug

#59 Version 1.5.1
  CONTRIBUTING.md
  README.md
  src/screens/Changelog.svelte
  src/screens/Profile.svelte
  src/screens/Setup.svelte
Labels: release
