Repository meower-media-co/Meower-Svelte, pull requests merged in 2023-03, with the labels that each got.

#97 Change password and delete account password confirmation patch
  src/lib/modals/ChangePassword.svelte
  src/lib/modals/DeleteAccount.svelte
  src/lib/modals/Login.svelte
  src/lib/modals/Signup.svelte
  src/screens/Changelog.svelte
  src/screens/Setup.svelte
Labels: future, for release 1/CL4 port

#108 Add MIT Licence
  LICENCE
Labels: URGENT, developer-facing

#115 Fix a few things with PostList
  src/lib/PostList.svelte
Labels: regression

#114 Fix text overflows
  src/lib/Container.svelte
Labels: high priority

#131 anti-impersonation in usernames
  src/lib/LiText.svelte
  src/lib/Post.svelte
  src/lib/ProfileView.svelte
Labels: URGENT
