Repository meower-media-co/Meower-Svelte, pull requests merged in 2024-02, with the labels that each got.

#219 Fix: Remove crash on unknown theme version
  src/lib/clmanager.js
  src/lib/modals/settings/CustomTheme.svelte
Labels: bug, URGENT, codebase issue, weird behavior

#218 Feat: Posts via the API.
  src/lib/PostList.svelte
Labels: URGENT, UX

#223 Backport 1.8.2
  package-lock.json
  package.json
  src/lib/Post.svelte
  src/lib/PostList.svelte
  src/lib/Report.svelte
  src/lib/Setup.svelte
  src/lib/Sidebar.svelte
  src/lib/TypingIndicator.svelte
  src/lib/clmanager.js
  src/lib/cloudlink.js
  src/lib/modals/AddImage.svelte
  src/lib/modals/moderation/ModPanel.svelte
  src/lib/modals/moderation/ModerateUser.svelte
  src/lib/modals/moderation/RestartServer.svelte
  src/lib/modals/settings/CustomTheme.svelte
  src/lib/stores.js
  src/lib/types.js
  src/lib/typingIndicator.js
  src/lib/version.js
  src/pages/about.svelte
Labels: release

#210 Fix: Molbile settings regression
  src/pages/settings.svelte
Labels: high priority, mobile, regression, UX

#208 Use bottom sheets for modals on mobile
  src/lib/Modal.svelte
Labels: enhancement, low priority, mobile, design, UX

#203 Mention and link fixes
  src/lib/Post.svelte
Labels: low priority
