Repository meower-media-co/Meower-Svelte, pull requests merged in 2024-07, with the labels that each got.

#242 api accounts support
  package-lock.json
  package.json
  src/lib/Setup.svelte
  src/lib/clmanager.js
  src/lib/modals/ConnectionFailed.svelte
  src/lib/modals/Login.svelte
  src/lib/modals/Signup.svelte
  src/lib/modals/moderation/ModPanel.svelte
  src/lib/modals/safety/ReportPost.svelte
  src/lib/modals/safety/ReportUser.svelte
  src/lib/modals/settings/ChangePassword.svelte
  src/lib/modals/settings/DeleteAccount.svelte
  src/lib/modals/settings/LogoutEverywhere.svelte
Labels: enhancement

#205 [1.9 (Hopefully)] New logo screen/intro animation
  index.html
  src/assets/style.css
  src/lib/Setup.svelte
  src/lib/modals/ServerSelector.svelte
  src/lib/modals/StartupError.svelte
  src/pages/_layout.svelte
Labels: enhancement, low priority, UX

#230 Feat: Full Mobile UI
  src/lib/Modal.svelte
  src/pages/settings.svelte
Labels: long-term, other branch, mobile, UX

#246 1.9.0 release
  .vscode/extensions.json
  CONTRIBUTING.md
  README.md
  index.html
  package-lock.json
  package.json
  src/assets/style.css
  src/lib/Badge.svelte
  src/lib/Modal.svelte
  src/lib/Post.svelte
  src/lib/PostList.svelte
  src/lib/Report.svelte
  src/lib/Setup.svelte
  src/lib/Sidebar.svelte
  src/lib/clmanager.js
  src/lib/modals/ConnectionFailed.svelte
  src/lib/modals/Login.svelte
  src/lib/modals/ServerSelector.svelte
  src/lib/modals/Signup.svelte
  src/lib/modals/StartupError.svelte
  src/lib/modals/moderation/ModPanel.svelte
  src/lib/modals/moderation/ModerateUser.svelte
  src/lib/modals/safety/ReportPost.svelte
  src/lib/modals/safety/ReportUser.svelte
  src/lib/modals/settings/ChangePassword.svelte
  src/lib/modals/settings/CustomTheme.svelte
  src/lib/modals/settings/DeleteAccount.svelte
  src/lib/modals/settings/LogoutEverywhere.svelte
  src/lib/modals/settings/SwitchBGMSFX.svelte
  src/lib/modals/settings/SwitchTheme.svelte
  src/lib/settings/BlockedUsers.svelte
  src/lib/settings/Personalization.svelte
  src/lib/settings/Profile.svelte
  src/lib/settings/ReportHistory.svelte
  src/lib/settings/Security.svelte
  src/lib/settings/Sessions.svelte
  src/lib/stores.js
  src/lib/unloadedprofile.js
  src/lib/version.js
  src/pages/_fallback.svelte
  src/pages/_layout.svelte
  src/pages/about.svelte
  src/pages/chats/[chatid].svelte
  src/pages/settings.svelte
Labels: release
